spring.application.name=ArgosApi-Java

server.port=${PORT:8080}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

weather.api.base-url=https://api.open-meteo.com/v1/forecast
nasa.api.key=${NASA_API_KEY}